export const HATALARI_YAKALA = "HATALARI_YAKALA";
export const MEVCUT_KULLANICI = "MEVCUT_KULLANICI";
export const MEVCUT_PROFIL = "MEVCUT_PROFIL";
export const PROFIL_YUKLENIYOR = "PROFIL_YUKLENIYOR";
export const PROFIL_BULUNAMADI = "PROFIL_BULUNAMADI";
export const MEVCUT_PROFILI_KALDIR = "MEVCUT_PROFILI_KALDIR";
export const BUTUN_PROFILLER = "BUTUN_PROFILLER";
